<?php

/**
 *  Copyright 2011 Graphity Team
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *  @package        graphity
 *  @author         Julius Šėporaitis <julius@graphity.org>
 *  @link           http://graphity.org/
 */

namespace Graphity;

/**
 * Some preinitialization that saves user some work.
 */
if(!defined('DS')) {
    define('DS', DIRECTORY_SEPARATOR);
}

if(!defined('PS')) {
    define('PS', PATH_SEPARATOR);
}

if(!defined('GRAPHITYDIR')) {
    define('GRAPHITYDIR', dirname(dirname(__FILE__)));
}

if(!class_exists('\\Graphity\\Loader')) {
    require_once(GRAPHITYDIR . DS . "Graphity" . DS . "Loader.php");
}

if(!class_exists('Annotation')) {
    require_once(GRAPHITYDIR . 
        DS . ".." . DS . ".." . DS . ".." .
        DS . "lib" . DS . "addendum" . DS . "lib" . DS . "annotations.php");

    // load Graphity related annotations
    set_include_path(get_include_path() . PS . 
        GRAPHITYDIR . DS . "Graphity" . DS . "Router" . DS . "Annotation");

    require_once("Path.php");
    require_once("Singleton.php");
}

/**
 * A simple bootstrapper for an application. It consumes an array generated by
 * bin/route_mapper.php and processes requests.
 */
class Application
{
    /**
     * @var \Graphity\Request $request
     */
    protected $request = null;

    /**
     * @var \Graphity\Router $router
     */
    protected $router = null;

    /**
     * Initializes application with the given route map.
     *
     * @param array $routeMap
     */
    public function __construct(array $routeMap)
    {
        $loader = new \Graphity\Loader("Graphity", GRAPHITYDIR);
        $loader->register();

        $this->request = new \Graphity\Request();
        $this->router = new \Graphity\Router($routeMap);
    }

    /**
     * Processes the HTTP Request. Finds an appropriate Resource, passes the control to it, and displays the resulting Response.
     */
    public function run()
    {
        try {
            $resource = $this->router->matchResource($this->request);

            $ref = new \ReflectionAnnotatedClass($resource);
            if($ref->hasAnnotation('Singleton') === false && $resource->exists() === false) {
                throw new WebApplicationException("Resource not found", Response::SC_NOT_FOUND);
            }
            if (!$resource->authorize()) {
                throw new WebApplicationException("Access denied", Response::SC_FORBIDDEN);
            }

            $methodName = $resource->getRouter()->matchMethod($resource);
            $response = $resource->$methodName();
            if($response === null) {
                throw new WebApplicationException("Method not allowed", Response::SC_METHOD_NOT_ALLOWED);
            }
            $response->commit(); // write status and headers
            $response->flushBuffer();
        } catch(\Graphity\WebApplicationException $e) {
            throw $e;
        } catch(\Exception $e) {
            // wrap all other Exceptions into WAE
            throw new \Graphity\WebApplicationException($e->getMessage(), $e->getCode(), $e);
        }
    }

    /**
     * Returns request
     *
     * @return \Graphity\Request
     */
    public function getRequest()
    {
        return $this->request;
    }

    /**
     * Returns router
     *
     * @return \Graphity\Router
     */
    public function getRouter()
    {
        return $this->router;
    }
}

